FreshFood/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

from .views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('', IndexView.as_view(), name='index'),
    path('user/', include('user.urls')),
    path('goods/', include('goods.urls')),

    path('ckeditor/', include('ckeditor_uploader.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/goods/urls.py
from django.urls import path
from django.conf.urls import url

from .views import DetailView, ListView

app_name = 'goods'
urlpatterns = [
    # path('detail/', DetailView.as_view(), name='detail')
    url(r'^detail/(?P<id>\d+)/$', DetailView.as_view(), name='detail'),
    # path('list/<int:p_number>', ListView.as_view(), name='list')
    # url(r'^list/(?P<type>\w+)/(?P<p_number>\d*)$', ListView.as_view(), name='list'),
    url(r'^list/(?P<type>\w+)/$', ListView.as_view(), name='list'),
    url(r'^list/(?P<type>\w+)/(?P<p_number>\d*)$', ListView.as_view(), name='list'),
]

apps/user/urls.py
from django.urls import path

from .views import RegisterView, LoingView, ConfirmView, UserCenterInfoView,UserCenterOrderView

app_name='user'
urlpatterns = [
    path('login/', LoingView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('confirm/', ConfirmView.as_view(), name='confirm'),
    path('user_center_info/', UserCenterInfoView.as_view(), name='user_center_info'),
    path('user_center_order/', UserCenterOrderView.as_view(), name='user_center_order'),
]

templates/cart.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-购物车</title>
	<link rel="stylesheet" type="text/css" href="css/reset.css">
	<link rel="stylesheet" type="text/css" href="css/main.css">
</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				<div class="login_info fl">
					欢迎您：<em>张 山</em>
				</div>
				<div class="login_btn fl">
					<a href="login.html">登录</a>
					<span>|</span>
					<a href="register.html">注册</a>
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="user_center_info.html">用户中心</a>
					<span>|</span>
					<a href="cart.html">我的购物车</a>
					<span>|</span>
					<a href="user_center_order.html">我的订单</a>
				</div>
			</div>
		</div>		
	</div>

	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;购物车</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>

	<div class="total_count">全部商品<em>2</em>件</div>	
	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>
	<ul class="cart_list_td clearfix">
		<li class="col01"><input type="checkbox" name="" checked></li>
		<li class="col02"><img src="images/goods/goods012.jpg"></li>
		<li class="col03">奇异果<br><em>25.80元/500g</em></li>
		<li class="col04">500g</li>
		<li class="col05">25.80元</li>
		<li class="col06">
			<div class="num_add">
				<a href="javascript:;" class="add fl">+</a>
				<input type="text" class="num_show fl" value="1">	
				<a href="javascript:;" class="minus fl">-</a>	
			</div>
		</li>
		<li class="col07">25.80元</li>
		<li class="col08"><a href="javascript:;">删除</a></li>
	</ul>

	<ul class="cart_list_td clearfix">
		<li class="col01"><input type="checkbox" name="" checked></li>
		<li class="col02"><img src="images/goods/goods003.jpg"></li>
		<li class="col03">大兴大棚草莓<br><em>16.80元/500g</em></li>
		<li class="col04">500g</li>
		<li class="col05">16.80元</li>
		<li class="col06">
			<div class="num_add">
				<a href="javascript:;" class="add fl">+</a>
				<input type="text" class="num_show fl" value="1">	
				<a href="javascript:;" class="minus fl">-</a>	
			</div>
		</li>
		<li class="col07">16.80元</li>
		<li class="col08"><a href="javascript:;">删除</a></li>
	</ul>
	

	<ul class="settlements">
		<li class="col01"><input type="checkbox" name="" checked=""></li>
		<li class="col02">全选</li>
		<li class="col03">合计(不含运费)：<span>¥</span><em>42.60</em><br>共计<b>2</b>件商品</li>
		<li class="col04"><a href="../templates/market/place_order.html">去结算</a></li>
	</ul>

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
</body>
</html>

templates/index.html
{% load static %}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">

<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">

	<title>天天生鲜-首页</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">


	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
{#	<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>#}

</head>

<body>

{#    顶部导航栏#}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">

                {% if request.user.is_authenticated %}
                    <div class="user_link fl">
                        <span>|</span>
                        <a href="{% url 'user:user_center_info' %}">用户中心</a>
                        <span>|</span>
                        <a href="cart.html">我的购物车</a>
                        <span>|</span>
                        <a href="user_center_order.html">我的订单</a>
                    </div>
                {% else %}
                    <div class="login_btn fl">
                        <a href="{% url 'user:login' %}">登录</a>
                        <span>|</span>
                        <a href="{% url 'user:register' %}">注册</a>
                    </div>
                {% endif %}

			</div>
		</div>
	</div>


{#    页面头部logo 搜索#}
	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="#" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">0</div>
		</div>
	</div>


{#    商品分类导航#}
	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>


{#    主体分类部分#}
	<div class="center_con clearfix">

{#        商品左侧细分栏#}
		<ul class="subnav fl">
			<li><a href="#model01" class="fruit">新鲜水果</a></li>

			<li><a href="#model02" class="seafood">海鲜水产</a></li>

			<li><a href="#model03" class="meet">猪牛羊肉</a></li>

			<li><a href="#model04" class="egg">禽类蛋品</a></li>

			<li><a href="#model05" class="vegetables">新鲜蔬菜</a></li>

			<li><a href="#model06" class="ice">速冻食品</a></li>
		</ul>

{#        轮播图#}
		<div class="slide fl">

			<ul class="slide_pics">
                {% for banner in banners %}
                    <li>
                        <a href="{{ banner.url }}"><img src="{{ banner.image.url }}" alt="幻灯片"></a>
                    </li>
                {% endfor %}
			</ul>

            <a href="#" class="unslider-arrow prev"></a>
            <a href="#" class="unslider-arrow next"></a>

		</div>

{#        右侧广告#}
		<div class="adv fl">
			<a href="#"><img src="{% static 'images/adv01.jpg' %}"></a>
			<a href="#"><img src="{% static 'images/adv02.jpg' %}"></a>
		</div>

	</div>


{#     水果信息#}
	<div class="list_model">

{#        详细信息头部#}
		<div class="list_title clearfix">
			<h3 class="fl" id="model01">新鲜水果</h3>

			<div class="subtitle fl">
				<span>|</span>

                {% for t_fruit in t_fruits %}
                    <a href="#">{{ t_fruit.name }}</a>
                {% endfor %}
			</div>

			<a href="{% url 'goods:list' 'xxsg' %}" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

{#        详细列表#}
		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{% static 'images/banner01.jpg' %}"></div>

			<ul class="goods_list fl">
                {% for fruit in fruits %}
                    <li>
					    <h4><a href="#">{{ fruit.name }} {{ fruit.specs }}</a></h4>
					    <a href="{% url 'goods:detail' fruit.id %}"><img src="{{ fruit.image.url }}"></a>
					    <div class="prize">¥ {{ fruit.price }}</div>
				    </li>
                {% endfor %}
			</ul>
		</div>

	</div>


{#    水产信息#}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model02">海鲜水产</h3>
			<div class="subtitle fl">
				<span>|</span>


				<a href="#">基围虾</a>

				<a href="#">扇贝</a>

			</div>
			<a href="" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{% static 'images/banner02.jpg' %}"></div>
			<ul class="goods_list fl">


				<li>
					<h4><a href="#">大青虾</a></h4>
					<a href="#"><img src="group1/M00/00/00/rBCzg1oKqKGAFAV-AAA5OS4Kl4c4097622"></a>
					<div class="prize">¥ 34.00</div>
				</li>

				<li>
					<h4><a href="#">北海道秋刀鱼</a></h4>
					<a href="#"><img src="group1/M00/00/00/rBCzg1oKqKuAavf8AAAkaP_7_187862565"></a>
					<div class="prize">¥ 50.00</div>
				</li>

				<li>
					<h4><a href="#">扇贝</a></h4>
					<a href="#"><img src="group1/M00/00/00/rBCzg1oKqLeATLQAAAAk8WCqqmI2968215"></a>
					<div class="prize">¥ 56.60</div>
				</li>

				<li>
					<h4><a href="#">基围虾</a></h4>
					<a href="#"><img src="group1/M00/00/00/rBCzg1oKqNKANQKOAAAk0DN4-yE7007770"></a>
					<div class="prize">¥ 100.90</div>
				</li>

			</ul>
		</div>
	</div>


{#    猪肉信息#}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model03">猪牛羊肉</h3>
			<div class="subtitle fl">
				<span>|</span>


				<a href="#">鸡肉</a>

			</div>
			<a href="#" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{% static 'images/banner03.jpg' %}"></div>
			<ul class="goods_list fl">


				<li>
					<h4><a href="#">猪肉</a></h4>
					<a href="#"><img src="group1/M00/00/00/rBCzg1oKqYSASWr0AAEVpb1YHUE4011268"></a>
					<div class="prize">¥ 23.99</div>
				</li>

				<li>
					<h4><a href="#">鸡腿</a></h4>
					<a href="#"><img src="group1/M00/00/00/rBCzg1oKq3CADiewAAA2_p7G96w3860045"></a>
					<div class="prize">¥ 45.00</div>
				</li>

				<li>
					<h4><a href="#">羊肉</a></h4>
					<a href="#"><img src="group1/M00/00/00/rBCzg1oKqhaAKgwkAAB6NOQDrpk3374052"></a>
					<div class="prize">¥ 56.99</div>
				</li>

				<li>
					<h4><a href="#">牛排</a></h4>
					<a href="#"><img src="group1/M00/00/00/rBCzg1oKqkuAUD0WAACwa3rCDPQ3064181"></a>
					<div class="prize">¥ 99.99</div>
				</li>

			</ul>
		</div>
	</div>

{#    禽类信息#}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model04">禽类蛋品</h3>
			<div class="subtitle fl">
				<span>|</span>


				<a href="#">盒装鸡蛋</a>

				<a href="#">鸭蛋</a>

			</div>
			<a href="#" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="group1/M00/00/00/rBCzg1oKebaAcEWVAAAqR4DoSUg3788077"></div>
			<ul class="goods_list fl">


				<li>
					<h4><a href="#">盒装鸡蛋</a></h4>
					<a href="#"><img src="group1/M00/00/00/rBCzg1oKqpeAZnSEAADUKbwLSqY1972845"></a>
					<div class="prize">¥ 23.00</div>
				</li>

				<li>
					<h4><a href="#">鸭蛋</a></h4>
					<a href="#"><img src="group1/M00/00/00/rBCzg1oKq0eAMxKFAAFC_2tSkFo4950479"></a>
					<div class="prize">¥ 45.00</div>
				</li>

				<li>
					<h4><a href="#">鹌鹑蛋</a></h4>
					<a href="#"><img src="group1/M00/00/00/rBCzg1oOlkyAHiH3AAGZ6KapWiA5556935"></a>
					<div class="prize">¥ 39.80</div>
				</li>

				<li>
					<h4><a href="#">鹅蛋</a></h4>
					<a href="#"><img src="group1/M00/00/00/rBCzg1oOlpqAOZ8gAADg_NUp5b47679136"></a>
					<div class="prize">¥ 49.90</div>
				</li>

			</ul>
		</div>
	</div>


{#    蔬菜信息#}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model05">新鲜蔬菜</h3>
			<div class="subtitle fl">
				<span>|</span>


				<a href="#">香菜</a>

				<a href="#">芹菜</a>

			</div>
			<a href="#" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="group1/M00/00/00/rBCzg1oKediAdUaaAAA-0ZoYkpM9419116"></div>
			<ul class="goods_list fl">


				<li>
					<h4><a href="#">白菜</a></h4>
					<a href="#"><img src="group1/M00/00/00/rBCzg1oKq5WAQnWDAADWHYeKaNI7952227"></a>
					<div class="prize">¥ 4.50</div>
				</li>

				<li>
					<h4><a href="#">芹菜</a></h4>
					<a href="#"><img src="group1/M00/00/00/rBCzg1oKq8yAa_CvAACIrzuaK646641688"></a>
					<div class="prize">¥ 3.50</div>
				</li>

				<li>
					<h4><a href="#">香菜</a></h4>
					<a href="#"><img src="group1/M00/00/00/rBCzg1oKq-iAUG8xAACNpHC0IEY3849954"></a>
					<div class="prize">¥ 7.90</div>
				</li>

				<li>
					<h4><a href="#">红辣椒</a></h4>
					<a href="#"><img src="group1/M00/00/00/rBCzg1oOlvWAB6BMAAHXO8pdocY9345486"></a>
					<div class="prize">¥ 11.00</div>
				</li>

			</ul>
		</div>
	</div>


{#    速冻信息#}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model06">速冻食品</h3>
			<div class="subtitle fl">
				<span>|</span>


				<a href="#">蟹棒</a>

				<a href="#">速冻水饺</a>

			</div>
			<a href="#" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="group1/M00/00/00/rBCzg1oKee-AGMXLAAA3sZPrVzQ0297876"></div>
			<ul class="goods_list fl">


				<li>
					<h4><a href="#">鱼丸</a></h4>
					<a href="#"><img src="group1/M00/00/00/rBCzg1oKrC-ACdOBAADZQphQJ2o3748807"></a>
					<div class="prize">¥ 66.00</div>
				</li>

				<li>
					<h4><a href="#">蟹棒</a></h4>
					<a href="#"><img src="group1/M00/00/00/rBCzg1oKrFeAJ9PuAABxy5vKkgY2006901"></a>
					<div class="prize">¥ 68.00</div>
				</li>

				<li>
					<h4><a href="#">虾丸</a></h4>
					<a href="#"><img src="group1/M00/00/00/rBCzg1oKrHGADF7jAABICav_wjk1418828"></a>
					<div class="prize">¥ 89.99</div>
				</li>

				<li>
					<h4><a href="#">速冻水饺</a></h4>
					<a href="#"><img src="group1/M00/00/00/rBCzg1oKrKaAFrRTAACMoBJXjDs3577358"></a>
					<div class="prize">¥ 20.00</div>
				</li>

			</ul>
		</div>
	</div>


{#    底部#}
	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>


	<script type="text/javascript" src="/static/js/unslider.js"></script>


    <script type="text/javascript">
        $(function () {
            var unslider =  $('.slide').unslider({
                speed: 500,
                delay: 3000,
	            complete: function() {},
	            keys: true,
	            dots: true,
	            fluid: false
            });

            $('.unslider-arrow').click(function() {
                var fn = this.className.split(' ')[1];
                unslider.data('unslider')[fn]();
            });
        })

    </script>



</body>
</html>

templates/place_order.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-提交订单</title>
	<link rel="stylesheet" type="text/css" href="css/reset.css">
	<link rel="stylesheet" type="text/css" href="css/main.css">
</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				<div class="login_info fl">
					欢迎您：<em>张 山</em>
				</div>
				<div class="login_btn fl">
					<a href="../templates/market/login.html">登录</a>
					<span>|</span>
					<a href="../templates/market/register.html">注册</a>
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="../templates/market/user_center_info.html">用户中心</a>
					<span>|</span>
					<a href="../templates/market/cart.html">我的购物车</a>
					<span>|</span>
					<a href="../templates/market/user_center_order.html">我的订单</a>
				</div>
			</div>
		</div>		
	</div>

	<div class="search_bar clearfix">
		<a href="../templates/market/index.html" class="logo fl"><img src="images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;提交订单</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>
	
	<h3 class="common_title">确认收货地址</h3>

	<div class="common_list_con clearfix">
		<dl>
			<dt>寄送到：</dt>
			<dd><input type="radio" name="" checked="">北京市 海淀区 东北旺西路8号中关村软件园 （李思 收） 182****7528</dd>
		</dl>
		<a href="../templates/market/user_center_site.html" class="edit_site">编辑收货地址</a>

	</div>
	
	<h3 class="common_title">支付方式</h3>	
	<div class="common_list_con clearfix">
		<div class="pay_style_con clearfix">
			<input type="radio" name="pay_style" checked>
			<label class="cash">货到付款</label>
			<input type="radio" name="pay_style">
			<label class="weixin">微信支付</label>
			<input type="radio" name="pay_style">
			<label class="zhifubao"></label>
			<input type="radio" name="pay_style">
			<label class="bank">银行卡支付</label>
		</div>
	</div>

	<h3 class="common_title">商品列表</h3>
	
	<div class="common_list_con clearfix">
		<ul class="goods_list_th clearfix">
			<li class="col01">商品名称</li>
			<li class="col02">商品单位</li>
			<li class="col03">商品价格</li>
			<li class="col04">数量</li>
			<li class="col05">小计</li>		
		</ul>
		<ul class="goods_list_td clearfix">
			<li class="col01">1</li>			
			<li class="col02"><img src="images/goods/goods012.jpg"></li>
			<li class="col03">奇异果</li>
			<li class="col04">500g</li>
			<li class="col05">25.80元</li>
			<li class="col06">1</li>
			<li class="col07">25.80元</li>	
		</ul>
		<ul class="goods_list_td clearfix">
			<li class="col01">2</li>			
			<li class="col02"><img src="images/goods/goods003.jpg"></li>
			<li class="col03">大兴大棚草莓</li>
			<li class="col04">500g</li>
			<li class="col05">16.80元</li>
			<li class="col06">1</li>
			<li class="col07">16.80元</li>	
		</ul>
	</div>

	<h3 class="common_title">总金额结算</h3>

	<div class="common_list_con clearfix">
		<div class="settle_con">
			<div class="total_goods_count">共<em>2</em>件商品，总金额<b>42.60元</b></div>
			<div class="transit">运费：<b>10元</b></div>
			<div class="total_pay">实付款：<b>52.60元</b></div>
		</div>
	</div>

	<div class="order_submit clearfix">
		<a href="javascript:;" id="order_btn">提交订单</a>
	</div>	

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>

	<div class="popup_con">
		<div class="popup">
			<p>订单提交成功！</p>
		</div>
		
		<div class="mask"></div>
	</div>
	<script type="text/javascript" src="js/jquery-1.12.2.js"></script>
	<script type="text/javascript">
		$('#order_btn').click(function() {
			localStorage.setItem('order_finish',2);

			$('.popup_con').fadeIn('fast', function() {

				setTimeout(function(){
					$('.popup_con').fadeOut('fast',function(){
						window.location.href = '../templates/market/index.html';
					});	
				},3000)
				
			});
		});
	</script>
</body>
</html>