FreshFood/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

from .views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('', IndexView.as_view(), name='index'),
    path('user/', include('user.urls')),
    path('goods/', include('goods.urls')),

    path('ckeditor/', include('ckeditor_uploader.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/user/urls.py
from django.urls import path

from .views import RegisterView, LoingView, ConfirmView, UserCenterInfoView,UserCenterOrderView

app_name='user'
urlpatterns = [
    path('login/', LoingView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('confirm/', ConfirmView.as_view(), name='confirm'),
    path('user_center_info/', UserCenterInfoView.as_view(), name='user_center_info'),
    path('user_center_order/', UserCenterOrderView.as_view(), name='user_center_order'),
]

apps/user/models.py
from datetime import datetime

from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


# 用户信息
class UserProfile(AbstractUser):
    nick_name = models.CharField('昵称', max_length=30)
    birthday = models.DateField('生日', null=True, blank=True)
    gender = models.CharField('性别', max_length=6, choices=(('male','男'),('female','女')), default='male')
    address = models.CharField('地址', max_length=100, default='')
    mobile = models.CharField('手机', max_length=11)
    image = models.ImageField('头像', max_length=100, upload_to='head/%Y/%m', default='head/default.png')

    class Meta:
        verbose_name = '用户信息'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.username

class Mailbox(models.Model):
    user  = models.OneToOneField('UserProfile' , on_delete=models.CASCADE, verbose_name='所属用户')
    code = models.CharField('验证码', max_length=100)
    email = models.EmailField('邮箱', max_length=20)
    type = models.CharField('发送类型', max_length=8, choices=(('register','注册'),('forget', '忘记密码')), default='register')
    send_time = models.DateTimeField('发送时间', default=datetime.now)

    class Meta:
        verbose_name = '邮箱验证'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.email

apps/user/forms.py
from django import forms

class RegisterForm(forms.Form):
    username = forms.CharField(min_length=4, max_length=20)
    pwd = forms.CharField(min_length=4, max_length=20)
    cpwd = forms.CharField(min_length=4, max_length=20)
    email = forms.EmailField()
    allow = forms.BooleanField()

class LoginForm(forms.Form):
    username = forms.CharField(min_length=4, max_length=20)
    pwd = forms.CharField(min_length=4, max_length=20)

apps/user/views.py
import datetime

from django.contrib.auth.hashers import make_password
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth import authenticate,login
from django.contrib.auth.backends import ModelBackend
from django.db.models import Q
from django.conf import settings

from .forms import RegisterForm, LoginForm
from .models import UserProfile, Mailbox
from tools import tools

class CustomBackend(ModelBackend):
    '''
    自定义登录验证
    '''
    def authenticate(self, request, username=None, password=None, **kwargs):
        try:
            user = UserProfile.objects.get(Q(username=username) | Q(email=username) | Q(mobile=username))
            if user.check_password(password):
                return user
        except Exception as e:
            return None

class RegisterView(View):
    '''
    注册视图
    '''
    def get(self, request):
        return render(request, 'user/register.html')

    def post(self, request):
        register_form =RegisterForm(request.POST)
        if register_form.is_valid():
            username = register_form.cleaned_data['username']
            pwd = register_form.cleaned_data['pwd']
            cpwd = register_form.cleaned_data['cpwd']
            email = register_form.cleaned_data['email']

            if UserProfile.objects.filter(username=username):
                u_msg = '该用户名已被注册'
                return render(request, 'user/register.html', {'u_msg':u_msg, 'register_form':register_form})
            if UserProfile.objects.filter(email=email):
                e_msg = '该邮箱已被注册'
                return render(request, 'user/register.html', {'e_msg': e_msg, 'register_form':register_form})

            if pwd == cpwd:
                new_user = UserProfile()
                new_user.username = username
                new_user.password = make_password(pwd)
                new_user.email = email
                new_user.is_active = False
                new_user.save()
                # 制作校验码
                code = tools.make_confirm_code(username)
                # 发送邮件
                result = tools.send_mail_to_user(email, code)
                if result:
                    # 存储至数据库
                    Mailbox.objects.create(user=new_user, code=code, email=email)
                return render(request, 'user/success.html', {'email':email})

        return render(request, 'user/register.html', {'register_form':register_form})

class LoingView(View):
    '''
    登录视图
    '''
    def get(self, request):
        return render(request, 'user/login.html')

    def post(self, request):
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            username = login_form.cleaned_data['username']
            pwd = login_form.cleaned_data['pwd']
            user = authenticate(username=username, password=pwd)
            if user is not None:
                if user.is_active:
                    remember = request.POST.get('remember', 0)
                    response = redirect('/')
                    if remember != 0:
                        response.set_cookie('username', username)
                        return response
                    else:
                        response.set_cookie('username', '', max_age=-1)
                        return response
                else:
                    msg = '用户邮箱还未激活！'
                    return render(request, 'user/login.html', {'msg':msg})

            return render(request, 'user/login.html', {'msg':'用户名或密码输入错误！'})
        return render(request, 'user/login.html', {'login_form':login_form})

class ConfirmView(View):
    '''
    激活用户
    '''
    def get(self, request):
        code = request.GET.get('code', '')
        if code:
            try:
                confirm = Mailbox.objects.get(code=code)
            except:
                msg = '无效的注册码！'
                return render(request, 'user/confirm.html', {'msg':msg})
            else:
                send_time = confirm.send_time
                now = datetime.datetime.now()
                if now > send_time + datetime.timedelta(settings.CONFIRM_DAYS):
                    confirm.user.delete()
                    confirm.delete()
                    msg = '邮件已经过期，原用户已失效，请重新注册！'
                    return render(request, 'user/confirm.html', {'msg':msg})
                else:
                    confirm.user.is_active = True
                    confirm.user.save()
                    confirm.delete()
                    msg = '感谢确认, 请使用该账户登录！'
                    return render(request, 'user/success.html', {'msg': msg})
        else:
            msg = '您的链接不正确！'
            return render(request, 'user/confirm.html', {'msg': msg})

class UserCenterInfoView(View):
    def get(self, request):
        active = 'info'
        return render(request, 'user/user_center_info.html',{'active':active})

class UserCenterOrderView(View):
    def get(self, request):
        active = 'order'
        return render(request, 'user/user_center_order.html', {'active':active})

templates/user/base_user_center.html
{% load static %}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-用户中心</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>

<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">

                {% if request.user.is_authenticated %}
                    <div class="login_info fl">
                        欢迎您：<em>{{ request.user.username }}</em>
                    </div>

                    <div class="user_link fl">
                        <span>|</span>
                        <a href="{% url 'user:user_center_info' %}">用户中心</a>
                        <span>|</span>
                        <a href="cart.html">我的购物车</a>
                        <span>|</span>
                        <a href="{% url 'user:user_center_order' %}">我的订单</a>
                    </div>
                {% else %}
                    <div class="login_btn fl">
                        <a href="{% url 'user:login' %}">登录</a>
                        <span>|</span>
                        <a href="{% url 'user:register' %}">注册</a>
                    </div>
                {% endif %}

			</div>
		</div>
	</div>

	<div class="search_bar clearfix">
		<a href="{% url 'index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
	</div>

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:user_center_info' %}" class="{% ifequal active 'info' %}active{% endifequal %}">· 个人信息</a></li>
				<li><a href="{% url 'user:user_center_order' %}" class="{% ifequal active 'order' %}active{% endifequal %}">· 全部订单</a></li>
				<li><a href="user_center_site.html">· 收货地址</a></li>
			</ul>
		</div>

        {% block content %}请填此块内容{% endblock %}

	</div>


	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>

</body>
</html>

templates/user/confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

</body>
</html>

templates/user/login.html
{% load static %}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">

<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-登录</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>

<body>

	<div class="login_top clearfix">
		<a href="{% url 'index' %}" class="login_logo"><img src="{% static 'images/logo02.png' %}"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">

				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="{% url 'user:register' %}">立即注册</a>
				</div>

				<div class="form_input">
					<form method="post" action="{% url 'user:login' %}">
                        {% csrf_token %}

						<input type="text" name="username" class="name_input" placeholder="请输入用户名" value="{{ request.COOKIES.username }}">
						<div class="{% if login_form.errors.username %}user_error{% endif %}">{{ login_form.errors.username }}</div>

						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="{% if login_form.errors.pwd %}pwd_error{% endif %}">{{ login_form.errors.pwd }}</div>

						<div class="more_input clearfix">
							<input type="checkbox" name="remember" value="1" checked="checked">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">

                        <div class="email_error">{{ msg }}</div>
					</form>
				</div>

			</div>
		</div>
	</div>

	<div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
</body>
</html>

templates/user/register.html
{% load static %}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-注册</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/register.js' %}"></script>
</head>

<body>
	<div class="register_con">

		<div class="l_con fl">
			<a class="reg_logo"><img src="{% static 'images/logo02.png' %}"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="{% url 'user:login' %}">登录</a>
			</div>

			<div class=" reg_form clearfix">
				<form id="tj" action="{% url 'user:register' %}" method="post">
                    {% csrf_token %}

				    <ul>
                        <li>
                            <label>用户名:</label>
                            <input type="text" name="username" id="username" value="{{ register_form.data.username }}">
                            <span class="{% if u_msg %}error_tip_show{% else %}error_tip{% endif %}">{{ u_msg }}</span>
                        </li>
                        <li>
                            <label>密码:</label>
                            <input type="password" name="pwd" id="pwd" value="{{ register_form.data.pwd }}">
                            <span class="error_tip">提示信息</span>
                        </li>
                        <li>
                            <label>确认密码:</label>
                            <input type="password" name="cpwd" id="cpwd" value="{{ register_form.data.cpwd }}">
                            <span class="error_tip">提示信息</span>
                        </li>
                        <li>
                            <label>邮箱:</label>
                            <input type="text" name="email" id="email" value="{{ register_form.data.email }}">
                            <span class="{% if e_msg %}error_tip_show{% else %}error_tip{% endif %}">{{ e_msg }}</span>
                        </li>
                        <li class="agreement">
                            <input type="checkbox" name="allow" id="allow" checked="checked">
                            <label>同意”天天生鲜用户使用协议“</label>
                            <span class="error_tip2">提示信息</span>
                        </li>
                        <li class="reg_sub">
                            <input type="submit" value="注 册">
                        </li>
				    </ul>

				</form>
			</div>

		</div>

	</div>

	<div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
</body>
</html>

templates/user/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>邮件发送成功</title>
</head>
<body>

{% if email %}
    <h1 style="text-align: center; margin-top: 100px">邮件已发送至{{ email }},请前往确认！</h1>
    <h2 style="text-align: center; margin-top: 150px">正在跳转至登录页面。。。</h2>
{% endif %}

{% if msg %}
    <h1 style="text-align: center; margin-top: 100px">{{ msg }}</h1>
    <h2 style="text-align: center; margin-top: 150px">正在跳转至登录页面。。。</h2>
{% endif %}



<script>
    window.setTimeout("window.location='{% url "user:login" %}'", 5000);
</script>

</body>
</html>

templates/user/user_center_info.html
{% extends 'user/base_user_center.html' %}
{% load static %}

{% block content %}
<div class="right_content clearfix">
    <div class="info_con clearfix">
        <h3 class="common_title2">基本信息</h3>
        <ul class="user_info_list">
            <li><span>用户名：</span>{{ request.user.username }}</li>
            <li><span>联系方式：</span>{{ request.user.mobile }}</li>
            <li><span>联系地址：</span>{{ request.user.address }}</li>
        </ul>
    </div>

    <h3 class="common_title2">最近浏览</h3>
    <div class="has_view_list">
        <ul class="goods_type_list clearfix">
            <li>
                <a href="detail.html"><img src="{% static 'images/goods/goods003.jpg' %}"></a>
                <h4><a href="detail.html">大兴大棚草莓</a></h4>
                <div class="operate">
                    <span class="prize">￥16.80</span>
                    <span class="unit">16.80/500g</span>
                    <a href="#" class="add_goods" title="加入购物车"></a>
                </div>
            </li>

            <li>
                <a href="#"><img src="{% static 'images/goods/goods004.jpg' %}"></a>
                <h4><a href="#">吐鲁番梨光杏</a></h4>
                <div class="operate">
                    <span class="prize">￥5.50</span>
                    <span class="unit">5.50/500g</span>
                    <a href="#" class="add_goods" title="加入购物车"></a>
                </div>
            </li>

            <li>
                <a href="#"><img src="images/goods/goods005.jpg"></a>
                <h4><a href="#">黄肉桃</a></h4>
                <div class="operate">
                    <span class="prize">￥10.00</span>
                    <span class="unit">10.00/500g</span>
                    <a href="#" class="add_goods" title="加入购物车"></a>
                </div>
            </li>

            <li>
                <a href="#"><img src="images/goods/goods006.jpg"></a>
                <h4><a href="#">进口西梅</a></h4>
                <div class="operate">
                    <span class="prize">￥28.80</span>
                    <span class="unit">28.8/500g</span>
                    <a href="#" class="add_goods" title="加入购物车"></a>
                </div>
            </li>

            <li>
                <a href="#"><img src="images/goods/goods007.jpg"></a>
                <h4><a href="#">香梨</a></h4>
                <div class="operate">
                    <span class="prize">￥6.45</span>
                    <span class="unit">6.45/500g</span>
                    <a href="#" class="add_goods" title="加入购物车"></a>
                </div>
            </li>
        </ul>
    </div>
</div>
{% endblock %}

templates/user/user_center_order.html
{% extends 'user/base_user_center.html' %}
{% load static %}


{% block content %}
<div class="right_content clearfix">
    <h3 class="common_title2">全部订单</h3>
    <ul class="order_list_th w978 clearfix">
        <li class="col01">2016-8-21 17:36:24</li>
        <li class="col02">订单号：56872934</li>
        <li class="col02 stress">未支付</li>
    </ul>

    <table class="order_list_table w980">
        <tbody>
        <tr>
            <td width="55%">
                <ul class="order_goods_list clearfix">
                    <li class="col01"><img src="images/goods02.jpg"></li>
                    <li class="col02">嘎啦苹果嘎啦苹果<em>11.80元/500g</em></li>
                    <li class="col03">1</li>
                    <li class="col04">11.80元</li>
                </ul>
                <ul class="order_goods_list clearfix">
                    <li class="col01"><img src="images/goods02.jpg"></li>
                    <li class="col02">嘎啦苹果嘎啦苹果<em>11.80元/500g</em></li>
                    <li class="col03">1</li>
                    <li class="col04">11.80元</li>
                </ul>
            </td>
            <td width="15%">33.60元</td>
            <td width="15%">待付款</td>
            <td width="15%"><a href="#" class="oper_btn">去付款</a></td>
        </tr>
        </tbody>
    </table>

    <ul class="order_list_th w978 clearfix">
        <li class="col01">2016-8-21 17:36:24</li>
        <li class="col02">订单号：56872934</li>
        <li class="col02 stress">已支付</li>
    </ul>
    <table class="order_list_table w980">
        <tbody>
        <tr>
            <td width="55%">
                <ul class="order_goods_list clearfix">
                    <li class="col01"><img src="images/goods02.jpg"></li>
                    <li class="col02">嘎啦苹果嘎啦苹果<em>11.80元/500g</em></li>
                    <li class="col03">1</li>
                    <li class="col04">11.80元</li>
                </ul>
                <ul class="order_goods_list clearfix">
                    <li class="col01"><img src="images/goods02.jpg"></li>
                    <li class="col02">嘎啦苹果嘎啦苹果<em>11.80元/500g</em></li>
                    <li class="col03">1</li>
                    <li class="col04">11.80元</li>
                </ul>
            </td>
            <td width="15%">33.60元</td>
            <td width="15%">已付款</td>
            <td width="15%"><a href="#" class="oper_btn">查看物流</a></td>
        </tr>
        </tbody>
    </table>

    <div class="pagenation">
        <a href="#">
            <上一页
        </a>
        <a href="#" class="active">1</a>
        <a href="#">2</a>
        <a href="#">3</a>
        <a href="#">4</a>
        <a href="#">5</a>
        <a href="#">下一页></a>
    </div>
</div>
{% endblock %}

templates/user/user_center_site.html
{% extends 'user/base_user_center.html' %}
{% load static %}


{% block content %}
<div class="right_content clearfix">
    <h3 class="common_title2">收货地址</h3>
    <div class="site_con">
        <dl>
            <dt>当前地址：</dt>
            <dd>北京市 海淀区 东北旺西路8号中关村软件园 （李思 收） 182****7528</dd>
        </dl>
    </div>
    <h3 class="common_title2">编辑地址</h3>
    <div class="site_con">
        <form>
            <div class="form_group">
                <label>收件人：</label>
                <input type="text" name="">
            </div>
            <div class="form_group form_group2">
                <label>详细地址：</label>
                <textarea class="site_area"></textarea>
            </div>
            <div class="form_group">
                <label>邮编：</label>
                <input type="text" name="">
            </div>
            <div class="form_group">
                <label>手机：</label>
                <input type="text" name="">
            </div>

            <input type="submit" name="" value="提交" class="info_submit">
        </form>
    </div>
</div>
{% endblock %}